# Generated by Django 3.1 on 2020-11-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.CharField(default='', max_length=20),
        ),
    ]
