# Generated by Django 2.2.14 on 2020-11-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opin',
            name='pub_date',
            field=models.DateTimeField(default='', null=True),
        ),
    ]
