# Generated by Django 2.2.14 on 2020-11-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0004_auto_20201123_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opin',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
