# Generated by Django 2.2.14 on 2020-11-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0007_auto_20201124_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opin',
            name='not_date',
        ),
        migrations.AddField(
            model_name='opin',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
