# Generated by Django 2.2.14 on 2020-11-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0008_auto_20201124_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opin',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
