# Generated by Django 2.2.14 on 2020-12-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0009_auto_20201124_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opin',
            old_name='pub_date',
            new_name='pup_date',
        ),
    ]
